# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    open-pull-requests-limit: 10
    schedule:
      interval: 'weekly'
      day: 'monday'
    reviewers:
      - 'derevnjuk'
    groups:
      webpack:
        patterns:
          - 'webpack*'
          - '@types/webpack*'
          - 'filemanager-webpack-plugin'
      commitlint:
        patterns:
          - '@commitlint/*'
      semantic-release:
        patterns:
          - 'semantic-release'
          - '@semantic-release/*'
      eslint:
        patterns:
          - 'eslint*'
          - '@typescript-eslint/*'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
      - dependency-name: 'devtools-protocol'
        update-types: ['version-update:semver-patch']
