name: CI / Coverage

on:
  workflow_dispatch:

  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install deps
        uses: ./.github/workflows/composite/npm

      - name: Execute test:cov npm script
        run: npm run test:cov

      - name: Send reports to Codeclimate
        uses: paambaati/codeclimate-action@v3.0.0
        if: ${{ hashFiles('coverage/lcov.info') }}
        env:
          CC_TEST_REPORTER_ID: dcb68bef247848ff70b9c592638236b22745fce5cd5b6a96192c5bf9521e45ee
        with:
          coverageLocations: coverage/lcov.info:lcov
