name: Semantic release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GPR_TOKEN }}

      - name: Install deps
        uses: ./.github/workflows/composite/npm

      - name: Release a new version
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GPR_TOKEN }}
